<?
$PERM["test"]["*"]="D";
$PERM["stati"]["*"]="D";
$PERM["custom_import"]["*"]="R";
$PERM["blog"]["*"]="R";
$PERM["catalog"]["8"]="W";
$PERM["catalog"]["*"]="R";
$PERM["basket"]["*"]="R";
$PERM["personal"]["8"]="W";
$PERM["news"]["8"]="W";
$PERM["about"]["8"]="W";
$PERM["index.php"]["8"]="W";
$PERM["/"]["*"]="R";
?>